{% set name = "pyamrex" %}
{% set version = "23.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AMReX-Codes/pyamrex/archive/refs/tags/{{ version }}.tar.gz
  sha256: 44dd3ab467260ea797dec4fcb939599fad811e8ac598bdc0ab05da24369606fa
  patches:
    # Adds pip_install_nodeps target, part of 23.11+
    #   https://github.com/AMReX-Codes/pyamrex/pull/203
    - 203.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang         # [win]
    - cmake
    - lld           # [win]
    - make          # [unix]
    - ninja         # [win]
    - libgomp       # [linux]
    - llvm-openmp   # [osx or win]
    - pkgconfig
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - amrex =={{ version }}
    - numpy
    - pip
    - pybind11
    - python
    - setuptools
    - wheel
  run:
    - amrex =={{ version }}
    - {{ pin_compatible('numpy') }}
    - python
    - libcxx  # [osx]

test:
  requires:
    - pytest
  imports:
    - amrex
  source_files:
    - tests/*
  files:
    - test.sh   # [unix]
    - test.bat  # [win]
  commands:
    # smoke tests: execute
    - ./test.sh      # [unix and build_platform == target_platform]
    - call test.bat  # [win]

about:
  home: https://pyamrex.readthedocs.io
  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE
  summary: GPU-Enabled, Zero-Copy AMReX Python Bindings including AI/ML

  description: |
    The Python binding pyAMReX bridges the worlds of block-structured codes and
    data science: it provides zero-copy application GPU data access for AI/ML,
    in situ analysis, application coupling and enables rapid, massively
    parallel prototyping. pyAMReX enhances the Block-Structured AMR Software
    Framework AMReX and its applications.
    AMReX is a software framework containing all the functionality to write
    massively parallel, block-structured adaptive mesh refinement (AMR)
    applications.

  doc_url: https://pyamrex.readthedocs.io
  dev_url: https://github.com/AMReX-Codes/pyamrex

extra:
  recipe-maintainers:
    - atmyers
    - ax3l
    - dpgrote
    - RemiLehe
    - roelof-groenewald
    - WeiqunZhang
